/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AurafitRouteImport } from './routes/aurafit'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as WardrobeRouteImport } from './routes/wardrobe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AurafitRoute = AurafitRouteImport.update({
  id: '/aurafit',
  path: '/aurafit',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aurafit': typeof AurafitRoute
  '/measurements': typeof MeasurementsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aurafit': typeof AurafitRoute
  '/measurements': typeof MeasurementsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aurafit': typeof AurafitRoute
  '/measurements': typeof MeasurementsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aurafit' | '/measurements' | '/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aurafit' | '/measurements' | '/wardrobe'
  id: '__root__' | '/' | '/aurafit' | '/measurements' | '/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AurafitRoute: typeof AurafitRoute
  MeasurementsRoute: typeof MeasurementsRoute
  WardrobeRoute: typeof WardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurafit': {
      id: '/aurafit'
      path: '/aurafit'
      fullPath: '/aurafit'
      preLoaderRoute: typeof AurafitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AurafitRoute: AurafitRoute,
  MeasurementsRoute: MeasurementsRoute,
  WardrobeRoute: WardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
