/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as AurafitRouteImport } from './routes/aurafit'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TryonRouteImport } from './routes/tryon'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as ApiAuraChatRouteImport } from './routes/api/aura-chat'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const AurafitRoute = AurafitRouteImport.update({
  id: '/aurafit',
  path: '/aurafit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TryonRoute = TryonRouteImport.update({
  id: '/tryon',
  path: '/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuraChatRoute = ApiAuraChatRouteImport.update({
  id: '/api/aura-chat',
  path: '/api/aura-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/aurafit': typeof AurafitRoute
  '/events': typeof EventsRoute
  '/measurements': typeof MeasurementsRoute
  '/studio': typeof StudioRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/aura-chat': typeof ApiAuraChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/aurafit': typeof AurafitRoute
  '/events': typeof EventsRoute
  '/measurements': typeof MeasurementsRoute
  '/studio': typeof StudioRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/aura-chat': typeof ApiAuraChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aura': typeof AuraRoute
  '/aurafit': typeof AurafitRoute
  '/events': typeof EventsRoute
  '/measurements': typeof MeasurementsRoute
  '/studio': typeof StudioRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/aura-chat': typeof ApiAuraChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aura'
    | '/aurafit'
    | '/events'
    | '/measurements'
    | '/studio'
    | '/tryon'
    | '/wardrobe'
    | '/api/aura-chat'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aura'
    | '/aurafit'
    | '/events'
    | '/measurements'
    | '/studio'
    | '/tryon'
    | '/wardrobe'
    | '/api/aura-chat'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/aura'
    | '/aurafit'
    | '/events'
    | '/measurements'
    | '/studio'
    | '/tryon'
    | '/wardrobe'
    | '/api/aura-chat'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuraRoute: typeof AuraRoute
  AurafitRoute: typeof AurafitRoute
  EventsRoute: typeof EventsRoute
  MeasurementsRoute: typeof MeasurementsRoute
  StudioRoute: typeof StudioRoute
  TryonRoute: typeof TryonRoute
  WardrobeRoute: typeof WardrobeRoute
  ApiAuraChatRoute: typeof ApiAuraChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurafit': {
      id: '/aurafit'
      path: '/aurafit'
      fullPath: '/aurafit'
      preLoaderRoute: typeof AurafitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryon': {
      id: '/tryon'
      path: '/tryon'
      fullPath: '/tryon'
      preLoaderRoute: typeof TryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aura-chat': {
      id: '/api/aura-chat'
      path: '/api/aura-chat'
      fullPath: '/api/aura-chat'
      preLoaderRoute: typeof ApiAuraChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuraRoute: AuraRoute,
  AurafitRoute: AurafitRoute,
  EventsRoute: EventsRoute,
  MeasurementsRoute: MeasurementsRoute,
  StudioRoute: StudioRoute,
  TryonRoute: TryonRoute,
  WardrobeRoute: WardrobeRoute,
  ApiAuraChatRoute: ApiAuraChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
